class Dicionario:
    estado_destino = "end-entrega-estado"
    cidade_destino = "end-entrega-cidade"
    tipo_pagamento = "pagamento-nome"
    status = "pedido-situacao"
    metodo_envio = "envio-nome"
    entregue = "Pedido Entregue"
    cancelado = "Pedido Cancelado"
    numero_pedido = "pedido-numero"
    cliente_id = "cliente-id"
    destinatario = "end-entrega-nome"
    valor_total = "pedido-valor-total"
    data_criacao = "pedido-data-criacao"
    genero = "sexo"
    id = "id"
    data_nascimento = "data-nascimento"
    data_cadastro = "data-criacao"
